// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ThemBang_CTBT1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ThemBang_CTBT1));
        
        string IMigrationMetadata.Id
        {
            get { return "202303230539107_ThemBang_CTBT1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
