// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InsertData_ChiTietBaiLuyenTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InsertData_ChiTietBaiLuyenTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202303170436019_InsertData_ChiTietBaiLuyenTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
