// <auto-generated />
namespace MyClass.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class insertRealDataLuyenTapTable_lan21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(insertRealDataLuyenTapTable_lan21));
        
        string IMigrationMetadata.Id
        {
            get { return "202303161106565_insertRealDataLuyenTapTable_lan21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
